### ISSUE TITLE
Try sink of CurrentValueSubject makes a crash with XCode 11.2.1.

### ISSUE THREAD

**Issue by meccatol** [broadwaylamb/OpenCombine#101] opened 2019-11-20 12:22 UTC
First of all, thanks for your hard work for this open-source, OpenCombine.

I used OpenCombine for using Combine at below iOS 13 in our project.
We successfully released a new version that has many codes operated by OpenCombine. It released with XCode 11.1 and OpenCombine '0.5.0' ver.

And we're preparing a new version with XCode 11.2.1 this time.

However, 0.5.0 ver has an issue in this XCode version.
I prepared a sample for repeating that crash, here is repo.
https://github.com/meccatol/OpenCombineTest

When I tested it with XCode 11.1, it not make a crash.
But It must make a crash with XCode 11.2.1.
(I also tested with Combine in the same project and same code, it's okay, it is not causing a crash.)

Crash happened at 'Subscribers.Sink.swift, line: 56.
```subscription.request(.unlimited), Error: EXC_BAD_ACCESS (code=2, address=0x10d96e889)```
But I don't know any idea for fixing this issue. :(

I hope that you would watch this issue soon, and I will be waiting for feedback. Thanks!

**Comment by broadwaylamb** [comment] 2019-11-20 13:34
Helli @meccatol!

Thank you for the bug report.

This looks like a Swift regression. I'm on it.

**Comment by broadwaylamb** [comment] 2019-11-20 14:25
Can you try setting `DEAD_CODE_STRIPPING = NO` in Xcode as a workaround? This fixed the issue for me.

<img width="730" alt="Screenshot 2019-11-20 at 17 24 41" src="https://user-images.githubusercontent.com/16309982/69246949-ab100d80-0bba-11ea-9aaa-72375691be87.png">

**Comment by broadwaylamb** [comment] 2019-11-20 14:33
Possibly related bug: https://bugs.swift.org/browse/SR-11564

Judging by the comments in JIRA, it broke a whole lot of projects. You are not alone.

People tell that the issue is fixed in Xcode 11.3 beta.

**Comment by meccatol** [comment] 2019-11-21 08:26
Thanks for fast-feedback!

I tested with ```DEAD_CODE_STRIPPING = NO```, it's not making a crash.

I hope it should be fixed in XCode 11.3 soon. :D

**Comment by broadwaylamb** [comment] 2019-11-21 08:28
You're welcome!

I'm gonna leave this issue open until this is fixed, so that if anyone encounters this problem too, they can easily find it.

**Comment by broadwaylamb** [comment] 2019-12-11 09:18
Xcode 11.3 has been released, the issue is fixed.

**Closed as completed by broadwaylamb** 2019-12-11 09:18 UTC
Labels: swift bug
