### ISSUE TITLE
Doesn't compile on macOS Monterey / XCode 13

### ISSUE THREAD

**Issue by vi4m** [broadwaylamb/OpenCombine#225] opened 2021-11-07 16:51 UTC
Hi! Thanks for this great project! However, compilation on Monterey, with the `OpenCombine 0.12.0` dep. fails with the following error:

`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/System/Library/Frameworks/Combine.framework/Modules/Combine.swiftmodule/x86_64-apple-macos.swiftinterface:1:1: error: failed to build module 'Combine' from its module interface; the compiler that produced it, 'Apple Swift version 5.5 (swiftlang-1300.0.29.207 clang-1300.0.28.1)', may have used features that aren't supported by this compiler, 'SwiftWasm Swift version 5.4.2 (swiftlang-5.4.0)'`

**Workaround:**

Switching to the XCode 12 (old version) on Monterey fixes the problem in the meantime.

**Comment by MaxDesiatov** [comment] 2021-11-07 19:16
Ugh, looks like there's no clear way to use Xcode 12 on Monterey, apparently? https://twitter.com/ethanhuang13/status/1442123371416731651

**Comment by MaxDesiatov** [comment] 2021-11-29 13:43
I think this is only reproducible when building with SwiftWasm 5.4 (and possibly 5.3). Should be fixed in SwiftWasm 5.5, please feel free to reopen if you're still seeing the issue after updating to SwiftWasm 5.5, or if SwiftWasm is not related to it.

**Closed as completed by MaxDesiatov** 2021-11-29 13:43 UTC
