### ISSUE TITLE
Missing Zip in OpenCombine

### ISSUE THREAD

**Issue by ManaliM27** [broadwaylamb/OpenCombine#203] opened 2021-02-03 20:32 UTC
Is it possible to zip 2 publishers similar to combine

**Comment by MaxDesiatov** [comment] 2021-02-22 18:06
Not until https://github.com/OpenCombine/OpenCombine/pull/109 is merged. Closing this as a duplicate of https://github.com/OpenCombine/OpenCombine/issues/1, this is where we track our progress for all of the operators.

**Closed as completed by MaxDesiatov** 2021-02-22 18:06 UTC
Labels: duplicate
